
%Run all tutorials. Usefull to check PNM_Matlab for debugging

Tutorial_PremiersPas
Tutorial_BasicPhysics
Tutorial_InjectionsMultiples
Tutorial_Condensation
%Tutorial_GeometryDefinition
%Tutorial_WettabilityAndClusterShape

